using System.Text.Json.Serialization;

namespace Z.Ai.Sdk.Core.Service.Videos;

/// <summary>
/// This class represents the video object containing details about the video generation
/// task.
/// </summary>
public record VideoObject
{
    /// <summary>
    /// Task order number generated by Z AI open platform, please use this order number
    /// when calling the request result interface
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = string.Empty;

    /// <summary>
    /// Model name
    /// </summary>
    [JsonPropertyName("model")]
    public string Model { get; init; } = string.Empty;

    /// <summary>
    /// Video generation result
    /// </summary>
    [JsonPropertyName("video_result")]
    public List<VideoResult>? VideoResult { get; init; }

    /// <summary>
    /// Processing status: PROCESSING (processing), SUCCESS (success), FAIL (failed) Note:
    /// Processing status requires querying to get results
    /// </summary>
    [JsonPropertyName("task_status")]
    public string TaskStatus { get; init; } = string.Empty;

    /// <summary>
    /// If BPO is performed, return the optimized prompt
    /// </summary>
    [JsonPropertyName("optimized_prompt")]
    public string? OptimizedPrompt { get; init; }

    /// <summary>
    /// Task number submitted by the user when requesting from the client or task number
    /// generated by the platform
    /// </summary>
    [JsonPropertyName("request_id")]
    public string? RequestId { get; init; }
}